apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o k8s_opencopilot
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o k8s_opencopilot
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/opencopilot-opencopilot-network: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: opencopilot
            - name: DB_HOST
              value: mysql
            - name: DB_PASSWORD
              value: dbpass
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: dbuser
          image: backend
          name: backend
          resources: {}
          volumeMounts:
            - mountPath: /app/shared_data
              name: shared-data
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
status: {}
