apiVersion: v1
data:
  CELERY_BACKEND: redis://redis:6379/1
  CELERY_BROKER: redis://redis:6379/0
  COPILOT_MODE: interactive
  LANGCHAIN_API_KEY: TOKEN_GOES_HERE
  LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
  LANGCHAIN_PROJECT: PROJECT_NAME_GOES_HERE
  LANGCHAIN_TRACING_V2: "true"
  LOCAL_IP: host.docker.internal
  MONGODB_URL: mongodb://dbuser:dbpass@mongodb:27017
  MYSQL_URI: mysql+pymysql://dbuser:dbpass@mysql:3306/opencopilot
  OPENAI_API_KEY: **7Wp
  OPENAI_API_TYPE: openai
  PINECONE_API_KEY: ""
  PINECONE_ENV: ""
  QDRANT_URL: http://qdrant:6333
  SCORE_THRESHOLD: "0.91"
  SELENIUM_GRID_URL: http://selenium:4444/wd/hub
  SHARED_FOLDER: /app/shared_data/
  STORE: QDRANT
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: llm-server-Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
