apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -o k8s_opencopilot
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: workers
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: workers
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -o k8s_opencopilot
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/opencopilot-opencopilot-network: "true"
        io.kompose.service: workers
    spec:
      containers:
        - args:
            - sh
            - -c
            - celery -A celery_app worker --loglevel=info
          env:
            - name: CELERY_BACKEND
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BACKEND
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: CELERY_BROKER
              valueFrom:
                configMapKeyRef:
                  key: CELERY_BROKER
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: COPILOT_MODE
              valueFrom:
                configMapKeyRef:
                  key: COPILOT_MODE
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: LANGCHAIN_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: LANGCHAIN_API_KEY
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: LANGCHAIN_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: LANGCHAIN_ENDPOINT
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: LANGCHAIN_PROJECT
              valueFrom:
                configMapKeyRef:
                  key: LANGCHAIN_PROJECT
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: LANGCHAIN_TRACING_V2
              valueFrom:
                configMapKeyRef:
                  key: LANGCHAIN_TRACING_V2
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: LOCAL_IP
              valueFrom:
                configMapKeyRef:
                  key: LOCAL_IP
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URL
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: MYSQL_URI
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_URI
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: OPENAI_API_TYPE
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_TYPE
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: PINECONE_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: PINECONE_API_KEY
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: PINECONE_ENV
              valueFrom:
                configMapKeyRef:
                  key: PINECONE_ENV
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: QDRANT_URL
              valueFrom:
                configMapKeyRef:
                  key: QDRANT_URL
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: SCORE_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  key: SCORE_THRESHOLD
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: SELENIUM_GRID_URL
              valueFrom:
                configMapKeyRef:
                  key: SELENIUM_GRID_URL
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: SHARED_FOLDER
              valueFrom:
                configMapKeyRef:
                  key: SHARED_FOLDER
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
            - name: STORE
              valueFrom:
                configMapKeyRef:
                  key: STORE
                  name: Users-shanurrahman-Documents-openchat_all-OpenCopilot-llm-server--env-docker
          image: workers
          name: workers
          resources: {}
          volumeMounts:
            - mountPath: /app/shared_data
              name: shared-data
      restartPolicy: Always
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
status: {}
